### PR TITLE
Fix bug when song names contain "." (period symbol)

### PR DESCRIPTION
**Pull request by Tomiscout**
Then it leads to TagLib exception and stops sync

### CODE REVIEW

**Comment by erwinkramer** [comment]
Ging to check it tomorrow. Are you sure you get the error on my latest build?

**Comment by Tomiscout** [comment]
I made a mistake trying to merge to the original repo. I am using your build, so yes. I haven't ran all the tests, but it fixed the bug for me and it works fine.

**Comment by Tomiscout** [comment]
Consistent results with this track:
https://soundcloud.com/tomas-gu-auskas/sets/test-playlist

**Comment by erwinkramer** [comment]
Already fixed in your other commit.

**Pull request closed without merging**
