### PR TITLE
Add option to download single track and minor refactoring

### PR DESCRIPTION
**Pull request by Tomiscout**
Playlist downloading functionality remains the same, i've only shortened Synchronize() method by moving some code for reusability into new method
`private string GetTrackLocalPath(Track track, string directoryPath)`

### CODE REVIEW

**Comment by erwinkramer** [comment]
nice, gonna test it

**Comment by erwinkramer** [comment]
Thank you for your commits. It's in the latest version (by restarting the latest version, so it updates).

I merged most of your code, please notice how i redone your code to update the progress bar for single track downloads.

**Comment by Tomiscout** [comment]
Nice to hear! I'ill check it out.

**Comment by Tomiscout** [comment]
Good job! Refactoring was really needed, so much scrolling...

**Pull request merged**
