### PR TITLE
Add formatter

### PR DESCRIPTION
**Pull request by HongSic**

### CODE REVIEW

**Review by erwinkramer — APPROVED** [review]

**Comment by erwinkramer** [comment]
I did some refactoring related to this merge with the following commit https://github.com/erwinkramer/SoundCloud-Playlist-Sync/commit/f2e5452bd12c50d0d1d3fb7ee8a76f3258613bce. So what was your idea with the metadata formatter?

**Comment by HongSic** [comment]
What you mean, JSON (manifest) file formatter or Filename formatter with ID3 tag?

image

**Comment by erwinkramer** [comment]
The id3 tag one.

**Comment by HongSic** [comment]
I will use taglib.

**Comment by HongSic** [comment]
Updated.

**Pull request merged**
